os: trusty

language: node_js
node_js:
- '8'

python:
  - 3.6

install:
- npm install -g data-cli
- pip3 install bs4

script: python3 scripts/extractLinks.py
env:
  global:
    username: Branko-Dj
  TRAVIS_SECURE_ENV_VARS: true