sudo: false
os: trusty

language: node_js
node_js:
- '8'

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      
before_install:
- "pip install bs4"

install:
- npm install -g data-cli

script: python3 scripts/extractLinks.py
env:
  global:
    username: Branko-Dj
  TRAVIS_SECURE_ENV_VARS: true