os: trusty

language: node_js
node_js:
- '8'

python:
  - 3.6
  
before_install:
  - apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
install:
- npm install -g data-cli
- pip3 install bs4
script: python3 scripts/extractLinks.py
env:
  global:
    username: examples
  TRAVIS_SECURE_ENV_VARS: true